apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment01
spec:
  selector:
    matchLabels:
      app: temp
  template:
    metadata:
      labels:
        app: temp
    spec:
      containers:
        - name: temp
          image: luc4sd3s0uz4/temp
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: temp
spec:
  selector:
    app: temp
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30000
  type: LoadBalancer
